on:
  push:
    branches:
    - main
    - release/*
jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/308965809546/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 'solstice-calendar-458717@appspot.gserviceaccount.com'
  
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v2'
